name = "gleam_ulid"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
description = "ULID implementation in Gleam (Erlang target only)"
licences = ["Apache-2.0"]
repository = { type = "github", user = "vtomilin", repo = "gleam_ulid" }
# links = [{ title = "Website", href = "" }]
internal_modules = [
"gleam_ulid/examples/*",
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
